[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "relic"
version = "0.1.0"
description = "Atmospheric retrievals using spectral light curves"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Chengzi Jiang"},
]
keywords = ["exoplanets", "atmospheric-retrieval", "spectroscopy"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
requires-python = ">= 3.10"

dependencies = [ 
    "exoiris==1.1.1",
    "pytransit",
    "numba",
    "numpy",
    "matplotlib",
    "h5py",
    "corner", 
    "petitRADTRANS",
    "nautilus-sampler",
    "mpi4py",
    "pyfastchem",
    "astropy",
    "scipy",
    "celerite2",
]

[project.urls]
Repository = "https://github.com/cjiang-exo/ReLiC"

[tool.setuptools.packages.find]
include = ["relic*"]

[tool.setuptools.package-data]
relic = ["py.typed"]
