[PATH]
input_file = [
  "../data/HD209458b/HST/results_G430L_20030503.h5",
  "../data/HD209458b/HST/results_G430L_20030625.h5",
  "../data/HD209458b/HST/results_G750L_20030531.h5",
  "../data/HD209458b/HST/results_G750L_20030705.h5",
  "../data/HD209458b/HST/WFC3G141_Iraclis_Deming12181.h5",
  "../data/HD209458b/JWST/NIRCAM_F322W2_new.h5",
  "../data/HD209458b/JWST/NIRCAM_F444W_new.h5",
]
output_dir = "../results/HD209458b/results-260503-joint/"

[STAR]
reference = "2017AJ....153..136S"
name = "HD209458"
teff = [6091, 50]
logg = [4.45, 0.02]
metal = [0.01, 0.05]
radius_rsun = [1.19, 0.02]
density_cgs = [1.04, 0.07]

[PLANET]
reference = "2017AJ....153..136S"
name = "HD209458b"
radius_rjup = [1.39, 0.02]
mass_mjup = [0.73, 0.04]
orb_t0_bjd = [2455216.405640, 0.000094]
orb_p_d = [3.52474859, 0.00000038]
transit_duration_d = [0.127, 0.0]
impact_parameter = [0.5056, 0.0133]
equilibrium_temperature = [1459, 12]

[ATMOSPHERE]
opacity_mode = "lbl"
pressure_bounds_log10bar = [-10, 2]
wavelength_bounds_micron = [0.298, 5.05]
chemical_species = ["H2O", "CO", "CO2", "CH4", "NH3", "SiO", "C2H2", "HCN", "Na", "K"]
rayleigh_species = ["H2", "He"]
continuum_species = ["H2--H2", "H2--He"]

[EXOIRIS]
bin_resolution = 100 # set to 0 for native resolution. Only used for JWST data.

[EXOIRIS.INSTRUMENT]
"0" = "HST/STIS G430L"
"1" = "HST/STIS G430L"
"2" = "HST/STIS G750L"
"3" = "HST/STIS G750L"
"4" = "HST/WFC3 G141"
"5" = "JWST/NIRCam F322W2"
"6" = "JWST/NIRCam F444W"

[EXOIRIS.WL_RANGE_MICRON]
"0" = []
"1" = []
"2" = []
"3" = []
"4" = []
"5" = [2.5, 4.0]
"6" = [4.0, 5.0]

[EXOIRIS.TIME_RANGE_BJD]
"0" = []
"1" = []
"2" = []
"3" = []
"4" = []
"5" = []
"6" = [2459890.03, 2459890.3]

[PRIORS]
rho = ["NP", 1.04, 0.07]
p = ["NP", 3.52474859, 0.00000038]
b = ["NP", 0.5056, 0.0133]
tc_00 = ["UP", 2459890.15, 2459890.25]
teff = ["NP", 6091, 50]
logg = ["NP", 4.45, 0.02]
metal = ["NP", 0.01, 0.05]
mp = ["NP", 0.73, 0.04]
ref_p = ["UP", -10, 2]
cloud_p = ["UP", -10, 2]
kir = ["UP", -5, 2]
gamma = ["UP", -3, 3]
tint = ["UP", 10, 500]
m2h = ["UP", -1, 3]
c2o = ["UP", 0.1, 1.6]
cloud_f = ["UP", 0.0, 1.0]
sigma_m_00 = ["UP", 0.5, 5]
sigma_m_01 = ["UP", 0.5, 5]
sigma_m_02 = ["UP", 0.5, 5]
sigma_m_03 = ["UP", 0.5, 5]
sigma_m_04 = ["UP", 0.5, 5]
sigma_m_05 = ["UP", 0.5, 5]
sigma_m_06 = ["UP", 0.5, 5]

[SAMPLER]
method = "emcee"
npools = 30
nwalkers = 60
niter_de = 500
niter_mcmc = 1000
