[PATH]
input_file = [
  "../data/HD209458b/JWST/NIRCAM_F322W2_new.h5",
  "../data/HD209458b/JWST/NIRCAM_F444W_new.h5",
]
output_dir = "../results/HD209458b/results-260510-benchmark-pix-isothermal/"

[STAR]
reference = "2017AJ....153..136S"
name = "HD209458"
teff = [6000, 60]
logg = [4.5, 0.05]
metal = [0.0, 0.05]
radius_rsun = [1.19, 0.02]
density_cgs = [1.04, 0.07]

[PLANET]
reference = "2017AJ....153..136S"
name = "HD209458b"
radius_rjup = [1.4, 0.02]
mass_mjup = [0.8, 0.04]
orb_t0_bjd = [2455216.405640, 0.000094]
orb_p_d = [3.52474859, 0.00000038]
transit_duration_d = [0.127, 0.0]
impact_parameter = [0.5, 0.0133]
equilibrium_temperature = [1459, 12]

[ATMOSPHERE]
opacity_mode = "lbl"
pressure_bounds_log10bar = [-8, 2]
wavelength_bounds_micron = [2.35, 5.1]
chemical_species = ["H2O", "CO", "CO2", "CH4", "NH3", "SiO", "C2H2", "HCN", ]
rayleigh_species = ["H2", "He"]
continuum_species = ["H2--H2", "H2--He"]

[EXOIRIS]
bin_resolution = 0 # set to 0 for native resolution. Only used for JWST data.

[EXOIRIS.INSTRUMENT] # NO SPACE 
0 = "JWST/NIRCam_F322W2"
1 = "JWST/NIRCam_F444W"

[EXOIRIS.NOISE_GROUP]
0 = 0
1 = 1 

[EXOIRIS.N_BASELINE]
0 = 1 # fourth order of orbital phases, second order of PC jitters 
1 = 1 # fourth order of orbital phases, second order of PC jitters 

[EXOIRIS.WL_RANGE_MICRON]
0 = [2.4, 4.0]
1 = [3.9, 5.0] 

[EXOIRIS.TIME_RANGE_BJD] 
0 = []
1 = [2459890.03, 2459890.3]

[PRIORS]
rho = ["NP", 1.00, 0.05]
p = ["NP", 3.52474859, 0.00000038]
b = ["NP", 0.50, 0.02]
tc_00 = ["UP", 2459890.15, 2459890.25]
teff = ["NP", 6000, 60]
logg = ["NP", 4.5, 0.05]
metal = ["NP", 0.0, 0.05]
sigma_m_00 = ["UP", 0.2, 5]
sigma_m_01 = ["UP", 0.2, 5] 
mp = ["NP", 0.8, 0.04]
ref_p = ["UP", -10, 2]
cloud_p = ["UP", -10, 2]
temp = ["UP", 300, 3000] 
m2h = ["UP", -1, 3]
c2o = ["UP", 0.1, 1.6]
cloud_f = ["UP", 0.0, 1.0]

[SAMPLER]
method = "emcee"
npools = 15
nwalkers = 60
niter_de = 1000
niter_mcmc = 2000
niter_white = 1000
