[PATH]
lightcurve_files = [
  "/work/relic/data/HD209458b/JWST/NIRCAM_F322W2_new.h5",
  "/work/relic/data/HD209458b/JWST/NIRCAM_F444W_new.h5",
]
spec_resolving_power_files = [  
  "/work/relic/data/resolving_power/NIRCam.dat",
  "/work/relic/data/resolving_power/NIRCam.dat",
]
output_dir = "/work/relic/results/HD209458b/results-260619-jwst-pix-fastchem/"

[STAR]
reference   = "2017AJ....153..136S"
name        = "HD209458" 
teff        = [6091, 50]
logg        = [4.45, 0.02]
metal       = [0.01, 0.05]
radius_rsun = [1.19, 0.02] 

[PLANET]
reference               = "2017AJ....153..136S"
name                    = "HD209458b"
transit_epoch_bjd       = [2455216.405640, 0.000094]
transit_period_d        = [3.52474859, 0.00000038]
transit_duration_d      = [0.127, 0.0]
radius_rjup             = [1.39, 0.02]  
mass_mjup               = [0.73, 0.04]
equilibrium_temperature = [1459, 12]
circular_orbit          = true

[ATMOSPHERE]
pressure_layers          = 101
pressure_bounds_log10bar = [-8, 2]
wavelength_bounds_micron = [2.35, 5.05]
chemical_species = [
  # "Na", "K", "TiO", "VO", "FeH", 
  "H2O", "CO", "CO2", "CH4", "NH3", 
  "C2H2", "HCN", "SiO", "H2S", "PH3"
]
rayleigh_species  = ["H2", "He"]
continuum_species = ["H2--H2", "H2--He"]
opacity_mode      = "lbl"
model_class       = "TP6FastChem"

[EXOIRIS]
instruments = [ # NO SPACE
  "JWST/NIRCam_F322W2", 
  "JWST/NIRCam_F444W"
]
wl_range_micron   = [ [2.4, 4.0], [3.9, 5.0] ]
time_range_bjd    = [ [], [2459890.03, 2459890.3] ]
noise_groups      = [0, 1]
n_baselines       = [2, 2] 
rebin_resolutions = [0, 0] # set to 0 for native resolution. 
noise_model        = "white_marginalized"

[PRIORS.TRANSIT]
rho         = ["NP", 1.04, 0.07, 0.7, 1.4, "stellar density", "cgs"]
p           = ["NP", 3.52474859, 0.00000038, 0, inf, "transit period", "days"]
b           = ["NP", 0.5056, 0.0133, 0, 1, "impact parameter", "R_s"]
tc_00       = ["UP", 2459890.15, 2459890.25, -inf, inf, "transit epoch", "BJD_TDB"]

[PRIORS.STAR]
teff        = ["NP", 6091, 50, 5000, 7000, "stellar effective temperature", "K"]
logg        = ["NP", 4.45, 0.02, 4, 5, "stellar gravity", "log10 cgs"]
metal       = ["NP", 0.01, 0.05, -1, 1, "stellar metallicity", ""]

[PRIORS.NOISE]
sigma_m_00  = ["UP", 0.2, 5, -inf, inf, "noise factor 00", ""]
sigma_m_01  = ["UP", 0.2, 5, -inf, inf, "noise factor 01", ""]

[PRIORS.ATMOSPHERE]
mp          = ["NP", 0.73, 0.04, 0.53, 0.93, "planet mass", "M_j"]
ref_p       = ["UP", -8, 2, -inf, inf, "reference pressure", "log10bar"] 
cloud_p     = ["UP", -8, 2, -inf, inf, "cloud-top pressure", "log10bar"] 
cloud_f     = ["UP", 0.0, 1.0, 0, 1.0, "cloud fraction", ""]
haze_f      = ["UP", -3, 3, -inf, inf, "haze factor", "log10"]
temp0       = ["UP", 100, 3000, -inf, inf, "temperature 0", "K"]
lga1        = ["UP", -1, 1, -inf, inf, "temperature profile parameter a1", ""]
lga2        = ["UP", -1, 1, -inf, inf, "temperature profile parameter a2", ""]
lgp1        = ["UP", -8, 0, -inf, inf, "temperature profile parameter p1", "log10bar"]
lgp2        = ["UP", -8, 0, -inf, inf, "temperature profile parameter p2", "log10bar"] 
m2h         = ["UP", -3, 3, -inf, inf, "atmospheric metallicity", "log10"]
c2o         = ["UP", 0.1, 2, -inf, inf, "C/O ratio", " "]

[SAMPLER]
method      = "dynesty" 
npools      = 60 
niter_white = 1000
nwalkers    = 60 
# niter_de    = 1000 
# niter_mcmc  = 2000 
bound       = "multi"
sample      = "rwalk"
n_live_points = 240 
n_effective = 400 
dlogz_init  = 0.1
# maxiter_batch = 2000
resume       = false
save_checkpoint = true

[FASTCHEM]
element_abundances = "/home/ubuntu/work/fastchem/lodders_2025.dat"
logk = "/home/ubuntu/work/fastchem/logK.dat"
logk_condensates = "/home/ubuntu/work/fastchem/logK_condensates.dat"
condensation_mode = "rainout"