[PATH]
input_file = [
  # "../data/HD209458b/HST/new_results_G430L_20030503.h5",
  # "../data/HD209458b/HST/new_results_G430L_20030625.h5",
  # "../data/HD209458b/HST/new_results_G750L_20030531.h5",
  # "../data/HD209458b/HST/new_results_G750L_20030705.h5",
  "../data/HD209458b/HST/WFC3G141_Iraclis_Deming12181.h5",
  "../data/HD209458b/JWST/NIRCAM_F322W2_new.h5",
  # "../data/HD209458b/JWST/NIRCAM_F444W_new.h5",
]
output_dir = "../results/HD209458b/results-test/"

[STAR]
reference   = "2017AJ....153..136S"
name        = "HD209458" 
teff        = [6091, 50]
logg        = [4.45, 0.02]
metal       = [0.01, 0.05]
radius_rsun = [1.19, 0.02] 

[PLANET]
reference               = "2017AJ....153..136S"
name                    = "HD209458b"
transit_epoch_bjd       = [2455216.405640, 0.000094]
transit_period_d        = [3.52474859, 0.00000038]
transit_duration_d      = [0.127, 0.0]
radius_rjup             = [1.39, 0.02]  
mass_mjup               = [0.73, 0.04]
equilibrium_temperature = [1459, 12]
circular_orbit          = true

[ATMOSPHERE]
pressure_bounds_log10bar = [-8, 2]
pressure_layers = 121
wavelength_bounds_micron = [1, 5.05]
chemical_species = ["H2O", "CO", "CO2", "CH4",]
rayleigh_species = ["H2", "He"]
continuum_species = ["H2--H2", "H2--He"]
opacity_mode = "lbl"

[EXOIRIS]
instruments = [ # NO SPACE
  "HST/WFC3_G141", 
  "JWST/NIRCam_F322W2", 
]
wl_range_micron   = [  [], [2.4, 4.0] ]
time_range_bjd    = [[], [],  ]
noise_groups      = [0, 1]
n_baselines       = [4, 2] 
rebin_resolutions = [0, 20] # set to 0 for native resolution. 
noise_model        = "white_marginalized"

[PRIORS.TRANSIT]
rho         = ["NP", 1.04, 0.07, 0.7, 1.4, "stellar density", "cgs"]
p           = ["NP", 3.52474859, 0.00000038, 0, inf, "transit period", "days"]
b           = ["NP", 0.5056, 0.0133, 0, 1, "impact parameter", "R_s"]
tc_00       = ["UP", 2459890.15, 2459890.25, -inf, inf, "transit epoch", "BJD_TDB"]

[PRIORS.STAR]
teff        = ["NP", 6091, 50, 5000, 7000, "stellar effective temperature", "K"]
logg        = ["NP", 4.45, 0.02, 4, 5, "stellar gravity", "log10 cgs"]
metal       = ["NP", 0.01, 0.05, -1, 1, "stellar metallicity", ""]

[PRIORS.NOISE]
sigma_m_00  = ["UP", 0.2, 5, -inf, inf, "noise factor 00", ""]
sigma_m_01  = ["UP", 0.2, 5, -inf, inf, "noise factor 01", ""] 

[PRIORS.ATMOSPHERE]
mp          = ["NP", 0.73, 0.04, 0.53, 0.93, "planet mass", "M_j"]
ref_p       = ["UP", -10, 2, -inf, inf, "reference pressure", "bar"]
cloud_p     = ["UP", -10, 2, -inf, inf, "cloud-top pressure", "bar"] 
cloud_f     = ["UP", 0.0, 1.0, 0, 1.0, "cloud fraction", ""]
tiso        = ["UP", 300, 3000, -inf, inf, "isothermal temperature", "K"] 
m2h         = ["UP", -1, 3, -1, 3, "atmospheric metallicity", ""]
c2o         = ["UP", 0.1, 1.6, 0.1, 1.6, "C/O ratio", ""]


[SAMPLER]
method      = "emcee"
npools      = 30
nwalkers    = 60
niter_de    = 200
niter_mcmc  = 200
niter_white = 200
