[PATH]
input_file = [
  "/home/ubuntu/work/relic/data/WASP39b/WASP39b_NIRSpec_NRS1_PCA1.h5",
  "/home/ubuntu/work/relic/data/WASP39b/WASP39b_NIRSpec_NRS2_PCA1.h5",
]
output_dir = "/home/ubuntu/work/relic/results/WASP39b/results-260611-PCA-r100-fastchem+SO2/"

[STAR]
reference   = "2018A&A...613A..41M"
name        = "WASP39" 
teff        = [5485, 76]
logg        = [4.453, 0.14]
metal       = [0.01, 0.09]
radius_rsun = [0.939, 0.022] 

[PLANET]
reference               = "2018A&A...613A..41M"
name                    = "WASP39b"
transit_epoch_bjd       = [2455342.96913, 0.00063]
transit_period_d        = [4.0552941, 0.0000034]
transit_duration_d      = [0.117, 0.0]
radius_rjup             = [1.279, 0.040]  
mass_mjup               = [0.281, 0.032]
equilibrium_temperature = [1166, 14]
circular_orbit          = true

[ATMOSPHERE]
pressure_layers          = 101
pressure_bounds_log10bar = [-8, 2]
wavelength_bounds_micron = [2.7, 5.2]
chemical_species = [ 
  "H2O", "CO", "CO2", "CH4", "NH3", 
  "C2H2", "HCN", "SiO", "H2S", "PH3", "SO2"
]
rayleigh_species  = ["H2", "He"]
continuum_species = ["H2--H2", "H2--He"]
opacity_mode      = "lbl"
model_class       = "TP6FastChem_SO2"

[EXOIRIS]
instruments = [ # NO SPACE
  "JWST/NIRSpec_NRS1", 
  "JWST/NIRSpec_NRS2"
]
wl_range_micron   = [ [ ], [-inf, 5.15] ]
time_range_bjd    = [ [], [ ] ]
noise_groups      = [0, 1] 
n_baselines       = [2, 2] 
rebin_resolutions = [100, 100] # set to 0 for native resolution. 
noise_model        = "white_marginalized"

[PRIORS.TRANSIT]
rho         = ["NP", 1.555, 0.080, 1.0, 2.0, "stellar density", "cgs"]
p           = ["NP", 4.0552941, 0.0000034, 0, inf, "transit period", "days"]
b           = ["NP", 0.5, 0.1, 0, 1, "impact parameter", "R_s"]
tc_00       = ["UP", 2455342.9, 2455343.0, -inf, inf, "transit epoch", "BJD_TDB"]

[PRIORS.STAR]
teff        = ["NP", 5485, 76, 5000, 6000, "stellar effective temperature", "K"]
logg        = ["NP", 4.453, 0.14, 4, 5, "stellar gravity", "log10 cgs"]
metal       = ["NP", 0.01, 0.09, -1, 1, "stellar metallicity", ""]

[PRIORS.NOISE]
sigma_m_00  = ["UP", 0.2, 5, -inf, inf, "noise factor 00", ""]
sigma_m_01  = ["UP", 0.2, 5, -inf, inf, "noise factor 01", ""]

[PRIORS.ATMOSPHERE]
mp          = ["NP", 0.281, 0.032, 0.12, 0.44, "planet mass", "M_j"]
ref_p       = ["UP", -8, 2, -inf, inf, "reference pressure", "log10bar"] 
cloud_p     = ["UP", -8, 2, -inf, inf, "cloud-top pressure", "log10bar"] 
cloud_f     = ["UP", 0.0, 1.0, 0, 1.0, "cloud fraction", ""]
haze_f      = ["UP", -3, 3, -inf, inf, "haze factor", "log10"]
temp0       = ["UP", 100, 3000, -inf, inf, "temperature 0", "K"]
lga1        = ["UP", -1, 1, -inf, inf, "temperature profile parameter a1", ""]
lga2        = ["UP", -1, 1, -inf, inf, "temperature profile parameter a2", ""]
lgp1        = ["UP", -8, 0, -inf, inf, "temperature profile parameter p1", "log10bar"]
lgp2        = ["UP", -8, 0, -inf, inf, "temperature profile parameter p2", "log10bar"] 
m2h         = ["UP", -3, 3, -inf, inf, "atmospheric metallicity", "log10"]
c2o         = ["UP", 1e-3, 2, -inf, inf, "C/O ratio", " "]
x_so2       = ["UP", -12, -1, -inf, inf, "SO2 abundance", "log10"]

[SAMPLER]
method      = "dynesty" 
npools      = 60 
niter_white = 1000
nwalkers    = 60 
# niter_de    = 1000 
# niter_mcmc  = 2000 
bound       = "multi"
sample      = "rwalk"
n_live_points = 240 
n_effective = 400 
dlogz_init  = 0.1
# maxiter_batch = 2000
resume       = false
save_checkpoint = true

[FASTCHEM]
element_abundances = "/home/ubuntu/work/fastchem/lodders_2025.dat"
logk = "/home/ubuntu/work/fastchem/logK.dat"
logk_condensates = "/home/ubuntu/work/fastchem/logK_condensates.dat"
condensation_mode = "rainout"